name: test-workflow.yml
run-name: Test Workflow
on: [push]
jobs:
  test:
    runs-on: ubuntu-22.04
    name: Test job
    container: rockylinux:9
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Docker
        run: dnf update -y && dnf install -y wget && curl -o /etc/yum.repos.d/docker-ce.repo 'https://download.docker.com/linux/centos/docker-ce.repo' && dnf install -y docker-ce docker-ce-cli containerd.io
      - name: Set Timezone
        run: ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
      - name: Get Time
        run: echo "IMAGE_VERSION=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: "ghcr.io/AzureZeng/test-image:${{ env.IMAGE_VERSION }}"