name: test-workflow
run-name: Test Workflow
on: [push]
jobs:
  test_job:
    runs-on: ubuntu-22.04
    container: rockylinux:9.0
    name: Test Job
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup dotnet 6
        run: dnf install dotnet-sdk-6.0 -y
      - name: Build Artifacts
        run: dotnet build -c Release
      - name: Save Build Data
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: ./artifacts/bin/MyConsoleApp/Release
    