name: test-workflow.yml
run-name: Test Workflow
on: [push]
jobs:
  test:
    runs-on: ubuntu-22.04
    name: Test job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: apt install gettext && type xgettext