name: test-workflow.yml
run-name: Test Workflow
on: [push]
jobs:
  test:
    runs-on: ubuntu-22.04
    name: Test job
    container: rockylinux:9
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo && sudo yum install -y docker-ce docker-ce-cli containerd.io
      - name: run
        run: docker run hello-world